// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "@/components/Navbar";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html
// //       lang="en"
// //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// //     >
// //       <body className="min-h-full flex flex-col">
// //         <Navbar/>
// //         {children}
// //         </body>
// //     </html>
// //   );
// // }


// // import { Noto_Sans_Bengali } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "@/components/Navbar";
// // import Footer from "@/components/Footer";

// // // Noto Sans Bengali ফন্ট কনফিগারেশন
// // const notoBengali = Noto_Sans_Bengali({
// //   weight: ["300", "400", "500", "600", "700"],
// //   subsets: ["bengali"],
// //   variable: "--font-noto-bengali", // Tailwind বা CSS-এর জন্য
// // });

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="bn">
// //       <body className={notoBengali.className}>
// //         <Navbar/>
// //         {children}
// //         <Footer/>
// //       </body>
// //     </html>
// //   );
// // }



// import { Noto_Sans_Bengali } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { Suspense } from "react";

// // Noto Sans Bengali ফন্ট কনফিগারেশন
// const notoBengali = Noto_Sans_Bengali({
//   weight: ["300", "400", "500", "600", "700"],
//   subsets: ["bengali"],
//   variable: "--font-noto-bengali",
// });

// // টিকারের জন্য নমুনা ডাটা (পরবর্তীতে API থেকে আনতে পারেন)
// const tickerProducts = [
//   { name: 'নাজিরশাইল চাল', price: 75, unit: 'কেজি', change: 2.5, emoji: '🍚' },
//   { name: 'মসুর ডাল', price: 130, unit: 'কেজি', change: -1.2, emoji: '🫘' },
//   { name: 'সয়াবিন তেল', price: 165, unit: 'লিটার', change: 0, emoji: '🍾' },
//   { name: 'আলু', price: '৫৫', unit: 'কেজি', change: -2.0, emoji: '🥔' },
//   { name: 'পেঁয়াজ', price: 90, unit: 'কেজি', change: 5.0, emoji: '🧅' },
//   { name: 'ডিম (ফার্ম)', price: 145, unit: 'ডজন', change: -3.5, emoji: '🥚' },
// ];

// export default function RootLayout({ children }) {
//   return (
//     <html lang="bn">
//       <body
//         className={`${notoBengali.className} flex min-h-screen flex-col`}
//       >
//         <Suspense
//           fallback={
//             <div className="h-16 border-b bg-white" />
//           }
//         >
//           <Navbar tickerProducts={tickerProducts} />
//         </Suspense>

//         <main className="flex-1">{children}</main>

//         <Footer />
//       </body>
//     </html>
//   );
// }



import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Suspense } from "react";

const notoBengali = Noto_Sans_Bengali({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["bengali"],
  variable: "--font-noto-bengali",
  display: "swap",
});

export const metadata = {
  title: "বাজার দর | বাংলাদেশের নিত্যপণ্যের দাম",
  description:
    "চাল, ডাল, তেল, সবজি, মাছ ও মাংসের বাজারদর দেখুন।",
};

// Sample ticker data
const tickerProducts = [
  {
    id: "chal",
    name: "নাজিরশাইল চাল",
    price: 75,
    unit: "কেজি",
    change: 2.5,
    emoji: "🍚",
  },
  {
    id: "dal",
    name: "মসুর ডাল",
    price: 130,
    unit: "কেজি",
    change: -1.2,
    emoji: "🫘",
  },
  {
    id: "oil",
    name: "সয়াবিন তেল",
    price: 165,
    unit: "লিটার",
    change: 0,
    emoji: "🍾",
  },
  {
    id: "alu",
    name: "আলু",
    price: 55,
    unit: "কেজি",
    change: -2,
    emoji: "🥔",
  },
  {
    id: "peyaj",
    name: "পেঁয়াজ",
    price: 90,
    unit: "কেজি",
    change: 5,
    emoji: "🧅",
  },
  {
    id: "dim",
    name: "ডিম (ফার্ম)",
    price: 145,
    unit: "ডজন",
    change: -3.5,
    emoji: "🥚",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body
        className={`${notoBengali.className} flex min-h-screen flex-col`}
      >
        <Suspense
          fallback={
            <div className="h-16 border-b bg-white" />
          }
        >
          <Navbar tickerProducts={tickerProducts} />
        </Suspense>

        <main className="flex-1">{children}</main>

        <Footer />
      </body>
    </html>
  );
}